import prisma from "@/lib/prisma";

export const SPEC_53_EVIDENCE_VERSION = "spec-53-evidence-v1";
const REQUIRED_TYPES = ["CUSTOM", "LOOKALIKE", "RETARGETING", "SAVED"] as const;
function family(value:string){const type=value.toUpperCase();if(type.includes("LOOKALIKE"))return "LOOKALIKE";if(type.includes("RETARGET")||["PAGE_ENGAGEMENT","VIDEO_VIEW","MESSAGE_ENGAGEMENT","WEBSITE_VISITOR"].includes(type))return "RETARGETING";if(type.includes("SAVED"))return "SAVED";if(type.includes("CUSTOM")||type==="CUSTOMER_LIST")return "CUSTOM";return type;}
export async function getSpec53Evidence(){
 const assets=await prisma.audienceAsset.findMany({where:{isActive:true},orderBy:{id:"asc"},select:{id:true,adAccountId:true,pageId:true,name:true,audienceType:true,productCategory:true,sourceKey:true,status:true,approvalStatus:true,learningStatus:true,isReusable:true,metaAudienceId:true,versions:{select:{id:true,isSelected:true,isUsed:true}},sources:{where:{isActive:true},select:{id:true}},usages:{select:{id:true}},performances:{select:{id:true}}}});
 const families=new Set(assets.map(a=>family(a.audienceType)));const fingerprints=new Map<string,number>();for(const a of assets){const key=[a.adAccountId,a.pageId??"",family(a.audienceType),a.productCategory??"",a.sourceKey??a.name.normalize("NFKC").toLowerCase()].join("|");fingerprints.set(key,(fingerprints.get(key)??0)+1);}const duplicateGroups=[...fingerprints.values()].filter(n=>n>1);
 const gaps=[] as Array<{reason:string;count?:number}>;if(assets.length===0)gaps.push({reason:"NO_PRODUCTION_AUDIENCE_ASSETS"});for(const type of REQUIRED_TYPES)if(!families.has(type))gaps.push({reason:`MISSING_${type}_AUDIENCE`});if(duplicateGroups.length)gaps.push({reason:"DUPLICATE_AUDIENCE_ASSETS",count:duplicateGroups.length});if(assets.some(a=>a.versions.length===0))gaps.push({reason:"AUDIENCE_WITHOUT_VERSION",count:assets.filter(a=>a.versions.length===0).length});if(!assets.some(a=>a.isReusable))gaps.push({reason:"NO_REUSABLE_AUDIENCE"});
 const pass=gaps.length===0;return{evidenceVersion:SPEC_53_EVIDENCE_VERSION,requirement:"AI creates and manages Custom, Lookalike, Retargeting and Saved Audience Assets without duplication for Net Profit",status:pass?"PASS_REAL":"NOT_PROVEN",pass,productionData:{activeAssets:assets.length,typeCoverage:Object.fromEntries(REQUIRED_TYPES.map(t=>[t,assets.filter(a=>family(a.audienceType)===t).length])),reusableAssets:assets.filter(a=>a.isReusable).length,versionedAssets:assets.filter(a=>a.versions.length>0).length,usedOrLinkedAssets:assets.filter(a=>a.usages.length>0||a.versions.some(v=>v.isUsed)).length,assetsWithPerformance:assets.filter(a=>a.performances.length>0).length,duplicateGroups:duplicateGroups.length,assets:assets.map(a=>({id:a.id,pageId:a.pageId,adAccountId:a.adAccountId,name:a.name,audienceType:a.audienceType,family:family(a.audienceType),productCategory:a.productCategory,status:a.status,approvalStatus:a.approvalStatus,learningStatus:a.learningStatus,isReusable:a.isReusable,versionCount:a.versions.length,sourceCount:a.sources.length,usageCount:a.usages.length,performanceRows:a.performances.length,metaCreated:Boolean(a.metaAudienceId)}))},capabilities:{create:true,reuse:true,adjustWithVersions:true,archiveWithoutDelete:true,duplicatePrevention:true,netProfitLearning:true},gapCount:gaps.length,gaps,safety:{readOnlyEvidence:true,metaMutationExecuted:false,realSpendUsed:false,budgetChanged:false,campaignPublished:false}};
}
